version: '3.9'
services:
  barcarena-sustentavel-postgresql:
    image: postgres:16.4
    container_name: barcarena-sustentavel-postgresql
    environment:
      POSTGRES_DB: barcarena_sustentavel
      POSTGRES_USER: barcarena_sustentavel
      POSTGRES_PASSWORD: barcarenasustentavel
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    networks:
      - barcarena-sustentavel-network
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

networks:
  barcarena-sustentavel-network:
    driver: bridge
