"""relação n-n entre as entidades Indicador e Referencias

Revision ID: 5bc263c39d32
Revises: c3c57b317d4f
Create Date: 2026-06-26 18:44:32.516464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc263c39d32'
down_revision: Union[str, None] = 'c3c57b317d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'IndicadorReferencia',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('fkIndicador_id', sa.Integer(), nullable=False),
        sa.Column('fkReferencia_id', sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        'fk_indicador_referencia',
        'IndicadorReferencia', 'Indicador',
        ['fkIndicador_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_referencia_indicador', 
        'IndicadorReferencia',
        'Referencias',
        ['fkReferencia_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IndicadorReferencia')