"""adicionar atributo pagina à entidade estudo_complementar

Revision ID: 62ec90ecd484
Revises: a73ce81a1629
Create Date: 2026-02-14 14:46:17.503359

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ec90ecd484'
down_revision: Union[str, None] = 'a73ce81a1629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EstudoComplementar', sa.Column('pagina', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('EstudoComplementar', 'pagina') #
    # ### end Alembic commands ###
